# Generated by Django 5.2.4 on 2025-11-20 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Llanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=80, null=True, verbose_name='Modelo')),
                ('ancho', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ancho')),
                ('alto', models.CharField(blank=True, max_length=10, null=True, verbose_name='Alto')),
                ('rin', models.CharField(blank=True, max_length=10, null=True, verbose_name='Rin')),
                ('radial', models.IntegerField(default=0, verbose_name='Radial')),
                ('creado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Llanta',
                'verbose_name_plural': 'Llantas',
                'db_table': 'Llanta',
                'ordering': ['marca', 'modelo', 'ancho', 'alto', 'rin'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_inventario', models.CharField(blank=True, max_length=64, null=True, verbose_name='Id primario')),
                ('producto_clave', models.CharField(blank=True, max_length=100, null=True, verbose_name='Producto/Clave')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('marca', models.CharField(blank=True, max_length=255, null=True, verbose_name='Marca')),
                ('ancho', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ancho')),
                ('alto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Alto')),
                ('rin', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rin')),
                ('existencia', models.IntegerField(default=0, verbose_name='Existencia')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('estatus', models.IntegerField(choices=[(0, 'Existe'), (1, 'Nuevo'), (2, 'Modificado'), (3, 'Sin recepción')], default=1, verbose_name='Estatus')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='almacen/', verbose_name='Imagen')),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='almacen1/', verbose_name='Imagen')),
                ('creado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llantas', to='taller.taller', to_field='id_empresa')),
            ],
            options={
                'verbose_name': 'Llanta',
                'verbose_name_plural': 'Llantas',
                'db_table': 'Inventario',
                'ordering': ['empresa', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_clave', models.CharField(blank=True, max_length=100, null=True, verbose_name='Producto/Clave')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio venta')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('talleres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taller.taller')),
                ('llantas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.llanta')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'db_table': 'Entrada',
                'ordering': ['talleres', 'producto_clave'],
            },
        ),
        migrations.CreateModel(
            name='MarcaLlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Marca')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'MarcaLlanta',
                'ordering': ['nombre'],
                'unique_together': {('nombre',)},
            },
        ),
        migrations.AddField(
            model_name='llanta',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.marcallanta'),
        ),
        migrations.AlterUniqueTogether(
            name='llanta',
            unique_together={('marca', 'modelo', 'ancho', 'alto', 'rin')},
        ),
    ]
