# Generated by Django 5.2.4 on 2025-11-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_options_alter_usuario_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('proveedor', 'Proveedor'), ('administrador', 'Administrador')], default='cliente', max_length=20, verbose_name='Rol'),
        ),
    ]
