# Generated by Django 5.2.4 on 2025-11-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('taller', 'Taller'), ('proveedor', 'Proveedor'), ('administrador', 'Administrador')], default='cliente', max_length=20, verbose_name='Rol'),
        ),
    ]
