# Generated by Django 5.2.4 on 2025-11-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
        ('usuario', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='talleres',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='taller.taller', verbose_name='Talleres'),
        ),
    ]
