# Generated by Django 5.2.4 on 2025-11-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empresa', models.CharField(max_length=64, unique=True, verbose_name='Id empresa')),
                ('razon_social', models.CharField(blank=True, max_length=100, null=True, verbose_name='Razón social')),
                ('direccion', models.CharField(blank=True, max_length=256, null=True, verbose_name='Dirección')),
                ('numero_exterior', models.CharField(blank=True, max_length=20, null=True, verbose_name='Núm. ext.')),
                ('numero_interior', models.CharField(blank=True, max_length=20, null=True, verbose_name='Núm. int.')),
                ('id_colonia', models.CharField(blank=True, max_length=40, null=True, verbose_name='Id colonia')),
                ('foto', models.TextField(blank=True, null=True, verbose_name='Taller')),
                ('colonia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Colonia')),
                ('codigo_postal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código postal')),
                ('id_municipio', models.CharField(blank=True, max_length=40, null=True, verbose_name='Id municipio')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio')),
                ('id_estado', models.CharField(blank=True, max_length=40, null=True, verbose_name='Id estado')),
                ('estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('telefono', models.CharField(blank=True, max_length=40, null=True, verbose_name='Teléfono')),
                ('longitud', models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitud')),
                ('latitud', models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitud')),
                ('estatus', models.IntegerField(choices=[(0, 'Existe'), (1, 'Nuevo'), (2, 'Modificado'), (3, 'Sin recepción')], default=1, verbose_name='Estatus')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='talleres/', verbose_name='Imagen')),
                ('creado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Talleres',
                'db_table': 'Taller',
                'ordering': ['razon_social'],
                'unique_together': {('razon_social',)},
            },
        ),
    ]
